# -*- coding: utf-8 -*-
"""rag_Your_Own_CV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mwRgcTFHkqde2wCQyvlm4DgVXYdxhSXC
"""

!pip install -U langchain
!pip install -U langchain-cohere
!pip install -U langchain-community
!pip install -U langchain-text-splitters
!pip install -U langchain-chroma
!pip install -U pypdf
!pip install -U chromadb

from google.colab import userdata
key=userdata.get('coherekey')

"""## Load PDF"""

from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader("/content/Medhat_Orabi_CV.pdf")

documents = loader.load()

print("Number of pages:", len(documents))

print(documents[0].page_content[:500])

"""## Chunking"""

from langchain_cohere import CohereEmbeddings

embeddings = CohereEmbeddings(
    model="embed-v4.0",
    cohere_api_key=key
)

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=800,
    chunk_overlap=100
)

chunks = text_splitter.split_documents(documents)

"""# ChromaDB"""

from langchain_chroma import Chroma

vectorstore = Chroma.from_documents(
    documents=chunks,
    embedding=embeddings,
    collection_name="pdf_rag"
)

"""## Retriever"""

retriever = vectorstore.as_retriever(
    search_kwargs={
        "k": 5
    }
)

query = "What is this document about?"

retrieved_docs = retriever.invoke(query)

for i, doc in enumerate(retrieved_docs):

    print(f"\n--- Document {i+1} ---")

    print(doc.page_content)

    print("Metadata:", doc.metadata)

"""## Generation

"""

from langchain_cohere import ChatCohere

llm = ChatCohere(
    model="command-a-03-2025",
    temperature=0,
    cohere_api_key=key
)

"""# Prompt"""

from langchain_core.prompts import ChatPromptTemplate

prompt = ChatPromptTemplate.from_template("""
You are a helpful assistant.

Answer the user's question using ONLY the context below.

If the answer cannot be found in the context,
say "I don't know."

Context:
{context}## top 1

Question:
{question}
""")

"""# RAG Chain"""

from langchain_core.runnables import RunnablePassthrough

def format_docs(docs):
    return "\n\n".join(
        doc.page_content
        for doc in docs
    )


rag_chain = (
    {"context": retriever | format_docs,
     "question": RunnablePassthrough()
     }
    | prompt
    | llm
)

questions = [
    'What are my main technical skills?',
    'What machine learning experience do I have?',
    'What projects are mentioned in my CV?',
    'What programming languages do I know?',
    'What training or internships have I completed?'
]

for question in questions:
    response = rag_chain.invoke(question)
    print(f"Q: {question}")
    print(f"A: {response.content if hasattr(response, 'content') else response}")
    print("-" * 40)